### ISSUE TITLE
MathKerning loses groups data when multiplied

### ISSUE THREAD

**Issue by LettError** [typesupply/fontMath#110]
[_processMathTwo()](https://github.com/typesupply/fontMath/blob/master/Lib/fontMath/mathKerning.py#L217) does not copy the data of `MathKerning.groups` which leads to wrong assumptions in `cleanup` and `guessPairType`, which can result in exceptions getting lost. 

A small test is here:
```python
from fontMath.mathKerning import MathKerning
from defcon.objects.font import Font

f = Font()
f.groups["public.kern1.groupA"] = ['one', 'Bee']
f.groups["public.kern2.groupB"] = ['two', 'Three']
f.kerning[('public.kern1.groupA', 'public.kern2.groupB')] = -100
m = MathKerning(f.kerning, f.groups)

print(m.groups())
print((m*1.0).groups())

>>> {'public.kern1.groupA': ['one', 'Bee'], 'public.kern2.groupB': ['two', 'Three']}
>>> {}
```

A bigger [test with related issue is here](https://github.com/LettError/ufoProcessor/issues/6).

**Comment by LettError** [comment]
It looks like it could be fixed by changing https://github.com/typesupply/fontMath/blob/master/Lib/fontMath/mathKerning.py#L222
to 
```python
ks = MathKerning(kerning, deepcopy(self._groups))
```

**Comment by typesupply** [comment]
The solution looks good to me!

**Comment by LettError** [comment]
Fixed.
